name: DB CI (lint)

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}-v1
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff>=3,<4"
      - name: Lint T-SQL (non-blocking)
        continue-on-error: true
        run: |
          echo "Linting all .sql in ./sql ..."
          test -d sql || (echo "::warning file=sql::'sql' folder not found"; exit 0)
          sqlfluff version
          sqlfluff lint sql --dialect tsql || echo "::warning::sqlfluff found issues (temporarily non-blocking)"
