name: DB CI (lint)

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install sqlfluff
        run: |
          python -m pip install --upgrade pip
          pip install "sqlfluff>=3,<4"

      - name: Determine files
        id: df
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            git diff --name-only origin/${{ github.base_ref }}... | grep -E '\.sql$' || true
          else
            git ls-files '*.sql'
          fi > files.txt
          echo "count=$(wc -l < files.txt)" >> $GITHUB_OUTPUT
          echo "Files to lint:"
          cat files.txt || true

      # Non-blocking while you iterate; remove continue-on-error to enforce later
      - name: Lint changed SQL (non-blocking while iterating)
        if: steps.df.outputs.count != '0'
        continue-on-error: true
        run: |
          xargs -a files.txt sqlfluff lint --dialect tsql || echo "::warning::sqlfluff found issues (temporarily non-blocking)"