name: Nightly DB reports

on:
  schedule:
    - cron: '30 06 * * *'
  workflow_dispatch:

jobs:
  build-and-export:
    runs-on: ubuntu-latest
    env:
      SA_PASSWORD: ${{ secrets.SA_PASSWORD }}

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
        ports:
          - 1433:1433
        # no custom options/health-cmd — we’ll wait from the runner

    steps:
      - uses: actions/checkout@v4

      - name: Install sqlcmd (mssql-tools18 & ODBC)
        run: |
          set -eux
          sudo apt-get update
          sudo apt-get install -y curl gnupg
          curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list > /dev/null
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18 unixodbc-dev

      - name: Wait for SQL to accept connections
        run: |
          set -eux
          for i in {1..60}; do
            /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -Q "SELECT 1" && break
            sleep 2
          done

      - name: Apply schema & seed (local paths)
        run: |
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -i scripts/apply_local.sql

      - name: Diagnose views presence
        run: |
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d MovieRentalDB -Q "SELECT DB_NAME() AS CurrentDB; SELECT name, type_desc FROM sys.objects WHERE name IN (vwOverdueRentals,vwLowInventory);"

      - name: Verify reporting views exist
        run: |
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d MovieRentalDB -Q "
            IF OBJECT_ID('dbo.vwOverdueRentals','V') IS NULL OR OBJECT_ID('dbo.vwLowInventory','V') IS NULL
              THROW 50010, 'Reporting views missing — ensure sql/02b_views_reports.sql is included', 1;
          "

      - name: Export reports
        run: |
          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d MovieRentalDB \
            -Q "SET NOCOUNT ON; SELECT * FROM dbo.vwOverdueRentals;" \
            -s "," -W -w 0 -o overdue_rentals.csv

          /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U SA -P "$SA_PASSWORD" -d MovieRentalDB \
            -Q "SET NOCOUNT ON; SELECT * FROM dbo.vwLowInventory;" \
            -s "," -W -w 0 -o low_inventory.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            overdue_rentals.csv
            low_inventory.csv
